@echo off
REM ------------------------------------------------------------------------------
REM This file was automatically generated by the Android build tools.
REM
REM It can be used to run the Gradle wrapper with the bundled Gradle
REM distribution. This file should be kept in version control.
REM ------------------------------------------------------------------------------

set SCRIPT_DIR=%~dp0
set GRADLE_WRAPPER_JAR=%SCRIPT_DIR%gradle\wrapper\gradle-wrapper.jar

if not exist "%GRADLE_WRAPPER_JAR%" (
  echo ERROR: Missing Gradle wrapper JAR: %GRADLE_WRAPPER_JAR% >&2
  echo You may need to run 'gradle wrapper' to generate it. >&2
  exit /b 1
)

java -jar "%GRADLE_WRAPPER_JAR%" %*